/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;
import Conexion.ConexionSQL;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author totit
 */
public class ListarDespacho extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarProducto
     */
    
    ConexionSQL cc = new ConexionSQL();
    Connection con =cc.conexion();
    private javax.swing.JMenuBar men;
    public ListarDespacho() {
        initComponents();
    }
    //Constructor que permite mostrar el menu//
    public ListarDespacho(javax.swing.JMenuBar menu) {
        initComponents();
        men = menu;
        listarDespacho();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BtnCerrar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListarDespacho = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setTitle("Lista de despachos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 33));

        ListarDespacho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(ListarDespacho);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 11, 930, 562));

        jLabel1.setText("Buscar por nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 114, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    public void listarDespacho(){
        
        String[] titulos={"ID Despacho","Nº Boleta","RUN","Nombre","Apellido","Producto","Cantidad","Direccion","Estado"};
        String[] registros = new String[9];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String SQL="select * from Despacho";
        
        try {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            
            while(rs.next()){
                
                registros[0]=rs.getString("idDespacho");
                registros[1]=rs.getString("n_boleta");
                registros[2]=rs.getString("run");
                registros[3]=rs.getString("nombre");
                registros[4]=rs.getString("apellido");
                registros[5]=rs.getString("producto");
                registros[6]=rs.getString("cantidad");
                registros[7]=rs.getString("direccion");
                registros[8]=rs.getString("estado");
                
                modelo.addRow(registros);
                
                ListarDespacho.setModel(modelo);
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al cargar los datos "+ e.getMessage());
        }
    }
    
    
   public void BuscarDespacho(String Dato){

        String[] titulos={"ID Despacho","Nº Boleta","RUN","Nombre","Apellido","Producto","Cantidad","Direccion","Estado"};
        String[] registros = new String[9];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL="select * from Despacho where nombre like '%"+Dato+"%'";

        try {

            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);


            while(rs.next()){

                registros[0]=rs.getString("idDespacho");
                registros[1]=rs.getString("n_boleta");
                registros[2]=rs.getString("run");
                registros[3]=rs.getString("nombre");
                registros[4]=rs.getString("apellido");
                registros[5]=rs.getString("producto");
                registros[6]=rs.getString("cantidad");
                registros[7]=rs.getString("direccion");
                registros[8]=rs.getString("estado");

                modelo.addRow(registros);

                ListarDespacho.setModel(modelo);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al cargar los datos "+ e.getMessage());
        }
    }
    
    
    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        men.show();
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        // TODO add your handling code here:
        BuscarDespacho(jTextFieldBuscar.getText());
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JTable ListarDespacho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
