/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;
import Conexion.ConexionSQL;
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author totit
 */
public class VerEstadosdespacho extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerEstadosdespacho
     */
    
    ConexionSQL cc = new ConexionSQL();
    Connection con =cc.conexion();
    private javax.swing.JMenuBar men;
    public VerEstadosdespacho() {
        initComponents();
    }
    //Constructor que permite mostrar el menu//
    public VerEstadosdespacho(javax.swing.JMenuBar menu) {
        initComponents();
        men = menu;
        VerEstadosDespacho();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCerrar = new javax.swing.JButton();
        BtnCambioEstado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscarEstado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListarEstado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        BtnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        BtnCerrar.setText("Cerrar");
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        BtnCambioEstado.setText("Cambiar estado");

        jLabel1.setText("Buscar por Nº Despacho:");

        jTextFieldBuscarEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarEstadoKeyReleased(evt);
            }
        });

        ListarEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ListarEstado);

        jLabel2.setText("*En desarrollo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextFieldBuscarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnCambioEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(BtnCambioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void VerEstadosDespacho(){
        
        String[] titulos={"ID Despacho","Estado"};
        String[] registros = new String[2];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String SQL="select * from Despacho";
        
        try {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            
            while(rs.next()){
                
                registros[0]=rs.getString("idDespacho");
                registros[1]=rs.getString("estado");
                
                modelo.addRow(registros);
                
                ListarEstado.setModel(modelo);
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al cargar los datos "+ e.getMessage());
        }
    }
    
    public void BuscarEstado(String Dato){

        String[] titulos={"ID Despacho","Estado"};
        String[] registros = new String[2];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL="select * from Despacho where idDespacho like '%"+Dato+"%'";

        try {

            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(SQL);


            while(rs.next()){

                registros[0]=rs.getString("idDespacho");
                registros[1]=rs.getString("estado");
                modelo.addRow(registros);

                ListarEstado.setModel(modelo);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al cargar los datos "+ e.getMessage());
        }
    }
    
    
    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        men.show();
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void jTextFieldBuscarEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarEstadoKeyReleased
        // TODO add your handling code here:
        BuscarEstado(jTextFieldBuscarEstado.getText());
        
    }//GEN-LAST:event_jTextFieldBuscarEstadoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCambioEstado;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JTable ListarEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBuscarEstado;
    // End of variables declaration//GEN-END:variables
}
